# Generated by Django 4.2.27 on 2026-08-01 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kn', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='💼', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], default='free', max_length=12)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title_kn', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('description_kn', models.TextField()),
                ('description_en', models.TextField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('daily', 'Daily shift'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=15)),
                ('salary_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('salary_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('salary_period', models.CharField(choices=[('month', 'Per month'), ('day', 'Per day'), ('hour', 'Per hour'), ('project', 'Per project')], default='month', max_length=10)),
                ('vacancies', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=10)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='published', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employerprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business')], max_length=12)),
                ('amount_paise', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('gateway_order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Fake job'), ('fee', 'Asking candidate for money'), ('wrong', 'Incorrect information'), ('abuse', 'Abusive or discriminatory'), ('other', 'Other')], max_length=12)),
                ('details', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobreport',
            constraint=models.UniqueConstraint(fields=('job', 'reporter'), name='one_report_per_user_job'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'city', '-created_at'], name='jobs_job_status_c40773_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='one_application_per_job'),
        ),
    ]
