# Generated by Django 4.2.27 on 2026-08-01 19:31

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, storage=accounts.models.PrivateResumeStorage(), upload_to=accounts.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), accounts.models.validate_resume_size]),
        ),
    ]
